sudo: required
services:
  - docker

before_insatll:
  - docker build -t willchang6471/docker-react -f Dockerfile.dev .

script:
  - docker run willchang6471/docker-react npm run test -- --coverage


